### ISSUE TITLE
Обновление версий PHP и Laravel

### ISSUE THREAD

**Issue by aletoropov** [Null-ch/PHP8.1-laravel8.3-nginx-MySQL-phpMyAdmin-NPM-Docker#1]
Можно обновить версии  PHP хотя бы до 8.1 и Laravel до 9-ой версии?

**Comment by Null-ch** [comment]
Привет, удалось самостоятельно накатить 9 лару или нужно дозалить?

**Comment by aletoropov** [comment]
Пока нет, пробовал в composer.json менять версию Laravel на ^9, но на моменте `composer update` вылетают ошибки. 
Потом еще попробую разобраться.

**Comment by Null-ch** [comment]
> Пока нет, пробовал в composer.json менять версию Laravel на ^9, но на моменте `composer update` вылетают ошибки. Потом еще попробую разобраться.

Для этого тебе саму конфигурацию докера менять не нужно

1. Установи себе лару нужной версии, например 9: composer create-project --ignore-platform-reqs laravel/laravel:^9.0 example-app (вызываем с флагом --ignore-platform-reqs чтобы не проверял версию пхп и не выдавал ошибку)
без проверки версии пхп на твоей машине
2. Перекинь туда докер файлы: папка _docker и docker-compose.yml
3. Запусти сборку контейнера: docker-compose up --build
4. Зайди в сам контейнер: docker exec -it project_app bash
5. Обнови зависимости: composer update
6. Сгенерируй ключ или зайди на запущенный проект: http://localhost:8076/ (или иной в зависимости от того как настроил докер и там сгенерируй)

**Comment by Null-ch** [comment]
> Пока нет, пробовал в composer.json менять версию Laravel на ^9, но на моменте `composer update` вылетают ошибки. Потом еще попробую разобраться.

Лара 9+ работает на пхп 8 и выше, просто закинь докеровские файлы в свою директорию с laravel 9 и собери контейнер

**Comment by aletoropov** [comment]
Хорошо, спасибо!
Вообще возьму этот контейнер себе за основу для работы с другими проектами.
